### ISSUE TITLE
[BACK] Argumentaire

### ISSUE THREAD

**Issue by heticeric** [blyndusk/PHRH-PWA#143]
Bon argumentaire, qui mériterait plus de détails : 
- des comparatifs techniques
- des mise en valeur de portions de code
- plus de mises en perspectives

**Comment by PAKdev1993** [comment]
Compris, attendez vous une correction pour l’évaluation suivante ?

**Comment by heticeric** [comment]
Je ne sais pas pour le moment.
Nous en reparlerons le moment venu.
