### ISSUE TITLE
[BACK] Fake server

### ISSUE THREAD

**Issue by heticeric** [blyndusk/PHRH-PWA#145]
Pourquoi avoir supprimer le serveur temporaire de données ?
Cela m'aurait intéressé de voir l'évolution des entités…

Du coup, supprimez le script du `package.json`

**Comment by heticeric** [comment]
Est-ce que le fichier `data.json` provient des données du `json-server` ?

**Comment by blyndusk** [comment]
@heticeric le serveur était comme vous l'avez dit, temporaire.

Il ne faisait rien de plus que de créer des routes à partir d'un fichier JSON statique.

Dès lors que le réel serveur NodeJS + Mongodb était mis en place, le serveur temporaire n'étais plus d'aucune utilité, car nous étions capable d'avoir le même résultat avec une même base de donnée.

------

le fichier `data.json` est justement la base du serveur temporaire et encore actuellement.

il a été genéré à l'aide de [scripts](https://github.com/blyndusk/PHRH-PWA/tree/ddd41641a6b130811e095dd6a4f08d1cf4f1fffa/server/fake-server/scripts) que j'ai crée pour rendre le procédé plus rapide.

Les données sont fausses, et sert de base à la construction de l'API.

Je vous invite à consulter @PAKdev1993 pour plus de précisions.

**Comment by heticeric** [comment]
👍
