### ISSUE TITLE
[BACK] MCD

### ISSUE THREAD

**Issue by heticeric** [blyndusk/PHRH-PWA#147]
Où est votre MCD ?

**Comment by heticeric** [comment]
Désormais que celui-ci est ajouté, quelques questions / remarques :

- La table Equipe est une table de jointure pour deux coéquipiers. Même si ce n'était pas dans le brief client, n'aurait-il pas été plus évolutif d'ajouter une clé primaire à cette table, permettant de créer des équipes de plus de 2 personnes ?
- Pourquoi avoir associer la table Visite à User (n->n) plutôt que Equipe ?
- Pourquoi la cardinalité à Vehicule n'appartient pas plutôt à Equipe également ?
- A quoi sert la clé Equipier_id dans User ?

Schéma à revoir.

**Comment by PAKdev1993** [comment]
> A quoi sert la clé Equipier_id dans User ?

C'est un artefact de l'ancien model, passé sous mes radars (a supprimer)

> Pourquoi la cardinalité à Vehicule n'appartient pas plutôt à Equipe également ?

Je l'avais déduis du brief, mais mon lien vers celui-ci pointe desormait sur une 404 donc je ne sais plus appuyer ce choix. L'utilisation d'un vehicule est une feature du Run Suivant il est possible que je revienne dessus quand je l'aborderai.

> Pourquoi avoir associer la table Visite à User (n->n) plutôt que Equipe ?

C'est un partis pris pour anticiper un besoin futur et pouvoir le réaliser sans avoir à faire de jointures entre Tables. Comme une "Visite" typé Contre-Visite peux s'effectuer a une seule personne, pour éventuellement réaliser simplement un historique ou un edt par visiteur, j'ai associé "Visite" a "User" et non à "Équipe"

> La table Equipe est une table de jointure pour deux coéquipiers. Même si ce n'était pas 
> dans le brief client, n'aurait-il pas été plus évolutif d'ajouter une clé primaire à cette 
> table, permettant de créer des équipes de plus de 2 personnes ?

C'est une erreur de mise à jour du model, il manque en effet la clé primaire "id_equipe" comme présent dans l'implémentation. Je ne comprend pas qu'est-ce qui n’était pas dans le brief ?

**Comment by heticeric** [comment]
> C'est un artefact de l'ancien model, passé sous mes radars (a supprimer)

Ton MCD ne semble pas avoir suivi les modifications de ton code en effet.
D'autant plus dommage dans la mesure où une partie de la note reposait sur ce schéma.

**Comment by heticeric** [comment]
> Je ne comprend pas qu'est-ce qui n’était pas dans le brief ?

Le fait qu'il puisse y avoir plus de deux visiteurs par équipe.
Je discute sur le fait de prendre par anticipation quelques décisions d'architecture qui puissent favoriser une meilleure évolution.
