### ISSUE TITLE
[BACK] Authentification

### ISSUE THREAD

**Issue by heticeric** [blyndusk/PHRH-PWA#148]
Absente ?

**Comment by PAKdev1993** [comment]
Je suis dans le premier Run définis par l’équipe cette feature n'en fais pas partie. 

La raison est la suivante :
Pour moi je manque d'infos pour définir vraiment la structure et la techno pour l'authentification et je n'ai pas envie de réécrire complétement une partie. 

Donc :
Je me suis dis que quand j'attaque Swagger et la partie sécurisation des requettes j’arrête le choix et démarre cette feature. Donc j'ai décidé de la placer en second run. (je vous avais par exemple posé la question la dernière fois sur Context par rapport a Redux et il en est sortis finalement que pour un version démo, contexte serai viable mais je ne sais pas si Context que j'ai appréhendé dans son fonctionnement elementaire peux être couplé a la partie sécurité).

**Comment by heticeric** [comment]
> je vous avais par exemple posé la question la dernière fois sur Context par rapport a Redux et il en est sortis finalement que pour un version démo, contexte serai viable mais je ne sais pas si Context que j'ai appréhendé dans son fonctionnement elementaire peux être couplé a la partie sécurité

As-tu suivi le cours que j'ai donné la fois précédente ?
Je vous y conseille de séparer les données en plusieurs contextes.
Du coup, la scalabilité de ce type d'architecture est tout à fait bonne.

Un context pour l'authentification est tout à fait envisageable.
