### ISSUE TITLE
[BACK] Qualité du code

### ISSUE THREAD

**Issue by heticeric** [blyndusk/PHRH-PWA#149]
- Aucun commentaire
- Nomenclatures de code non suivies
- Mongoose : bien !
- Commentaire d'API swagger bien

**Comment by blyndusk** [comment]
@heticeric Je vous invite à vous diriger vers la branche [feature/server-global](https://github.com/blyndusk/PHRH-PWA/tree/feature/server-global) pour les dernières mise à jour.

**Comment by heticeric** [comment]
@blyndusk Je corrige pur le moment le rendu d'expertise du 1er semestre.

**Comment by PAKdev1993** [comment]
> Aucun commentaire

De quels commentaires parle t'on ? Mon code est globalement commenté, je rajoute les commentaires après avoir validé le fonctionnement et la structure de mon code pour la version en cours du coup je ne comprend pas.

> Nomenclatures de code non suivies

Pourrai-je s'il vous plait savoir de quelle nomenclature il s'agit pour corriger ?

**Comment by heticeric** [comment]
> Pourrai-je s'il vous plait savoir de quelle nomenclature il s'agit pour corriger ?

La tienne !
Parfois le nom des tables débutent par une majuscule, d'autres non.
Le nom des champs et des clé pourraient également bénéficier d'une certaine standardisation.

Sinon, je n'ai pas de règles a priori.

**Comment by heticeric** [comment]
> De quels commentaires parle t'on ? Mon code est globalement commenté

Trop globalement oui.
Cela le rend difficile à appréhender et du coup à partager.
