### ISSUE TITLE
[FRONT] Nombre de commits de Nino

### ISSUE THREAD

**Issue by heticeric** [blyndusk/PHRH-PWA#151]
Sur quelle partie Nino est-il intervenu ?
Il n'a qu'un seul commit !

**Comment by blyndusk** [comment]
@heticeric , @ninolam n'a pas qu'un seul commit.

Il en a un seul en étant enregistré en tant que [`@ninolam`](https://github.com/ninolam).

Le problème doit venir de son authentification du côté de sa machine, vous pouvez voir cela car il est authentifié en tant que `Nino Lamoureux` sur tous ces autres commits.

Je vais voir ce que je peux faire pour l'authentifier.

**Comment by heticeric** [comment]
@blyndusk regarde dans les insights.
Aucun autre contributeurs…

Qu'en dis @ninolam ?

**Comment by blyndusk** [comment]
Je sais bien qu'il n'est pas visible dans les insights, c'est pourquoi je vous explique la raison ici.

Vous pouvez voir les commits de Nino sur [cette](https://github.com/blyndusk/PHRH-PWA/commits/feature/client-cruds) branche par exemple, simplement est authentifié en tant que "Nino Lamoureux".

Également [ici](https://github.com/blyndusk/PHRH-PWA/commits/feature/client-cruds?after=2abd56027d9eeb22c013ad2952a6d20589221990+104), il est authentifié cette fois en tant que "Nino Lam"

**Comment by heticeric** [comment]
Ok, je viens de voir. Merci.
