### ISSUE TITLE
[FRONT] Argumentaire

### ISSUE THREAD

**Issue by heticeric** [blyndusk/PHRH-PWA#152]
Plus qu'insuffisant.
Aucune argumentation. A revoir !

**Comment by blyndusk** [comment]
L'argumentaire est pourtant ici: https://github.com/blyndusk/PHRH-PWA/blob/master/client/README.md

**Comment by heticeric** [comment]
Certes.
Mais https://www.larousse.fr/dictionnaires/francais/argumentaire/5211

**Comment by blyndusk** [comment]
Cette définition a-t-elle été fournie lors de la demande initiale ?

**Comment by heticeric** [comment]
Tu te moques de moi @blyndusk ?
Il faut vous fournir les définitions des mots employés dans les critères d'évaluation en plus ?
Peut-être aussi vous fournir un dictionnaire, voire de vous apprendre à lire ?

**Comment by blyndusk** [comment]
Nous parlerons de vive voix. 

Alexandre.
